openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/JamesKotov/p2u-test/1.0.0
info:
  description: This is a simple API for p2u test work
  version: "1.0.0"
  title: Simple API
  contact:
    email: james.kotoff@gmail.com
tags:
  - name: Health
    description: Healthcheck api
  - name: Html
    description: Html pages
  - name: Api
    description: Api pages

paths:
  /:
    get:
      tags:
        - Html
      summary: Offers list
      operationId: offersList
      responses:
        '200':
          description: empty object that means all ok
          headers:
            X-Request-ID:
              schema:
                type: string
                format: uuid
                description: Unique id of current request, to match records in log
                example: 'f7314976-f9fc-450f-b46e-b77fbe793f94'
            Date:
              schema:
                type: string
                description: Current server date and time
                example: 'Thu, 24 Jan 2019 13:03:49 GMT'
          content:
            text/html:
              schema:
                type: string

        '500':
          description: Internal Server Error
          headers:
            X-Request-ID:
              schema:
                type: string
                format: uuid
                description: Unique id of current request, to match records in log
                example: 'f7314976-f9fc-450f-b46e-b77fbe793f94'
            Date:
              schema:
                type: string
                description: Current server date and time
                example: 'Thu, 24 Jan 2019 13:03:49 GMT'
          content:
            text/html:
              schema:
                type: string

  /offers/{offerId}:
    get:
      tags:
        - Html
      summary: Offer page
      operationId: offerPage
      parameters:
        - in: path
          name: offerId
          required: true
          schema:
            type: string
            example: '1'
          description: Offer id
      responses:
        '200':
          description: empty object that means all ok
          headers:
            X-Request-ID:
              schema:
                type: string
                format: uuid
                description: Unique id of current request, to match records in log
                example: 'f7314976-f9fc-450f-b46e-b77fbe793f94'
            Date:
              schema:
                type: string
                description: Current server date and time
                example: 'Thu, 24 Jan 2019 13:03:49 GMT'
          content:
            text/html:
              schema:
                type: string

        '404':
          description: Not found
          headers:
            X-Request-ID:
              schema:
                type: string
                format: uuid
                description: Unique id of current request, to match records in log
                example: 'f7314976-f9fc-450f-b46e-b77fbe793f94'
            Date:
              schema:
                type: string
                description: Current server date and time
                example: 'Thu, 24 Jan 2019 13:03:49 GMT'
          content:
            text/html:
              schema:
                type: string

        '500':
          description: Internal Server Error
          headers:
            X-Request-ID:
              schema:
                type: string
                format: uuid
                description: Unique id of current request, to match records in log
                example: 'f7314976-f9fc-450f-b46e-b77fbe793f94'
            Date:
              schema:
                type: string
                description: Current server date and time
                example: 'Thu, 24 Jan 2019 13:03:49 GMT'
          content:
            text/html:
              schema:
                type: string
    post:
      tags:
        - Api
      summary: Adding new ticket
      parameters:
        - in: path
          name: offerId
          required: true
          schema:
            type: string
            example: '1'
          description: Offer id
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                order_id:
                  type: string
                order_sum:
                  type: string
                comment:
                  type: string
                clicks:
                  type: string


      responses:
        '200':
          description: Internal Server Error
          headers:
            X-Request-ID:
              schema:
                type: string
                format: uuid
                description: Unique id of current request, to match records in log
                example: 'f7314976-f9fc-450f-b46e-b77fbe793f94'
            Date:
              schema:
                type: string
                description: Current server date and time
                example: 'Thu, 24 Jan 2019 13:03:49 GMT'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Internal Server Error
          headers:
            X-Request-ID:
              schema:
                type: string
                format: uuid
                description: Unique id of current request, to match records in log
                example: 'f7314976-f9fc-450f-b46e-b77fbe793f94'
            Date:
              schema:
                type: string
                description: Current server date and time
                example: 'Thu, 24 Jan 2019 13:03:49 GMT'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '404':
          description: Internal Server Error
          headers:
            X-Request-ID:
              schema:
                type: string
                format: uuid
                description: Unique id of current request, to match records in log
                example: 'f7314976-f9fc-450f-b46e-b77fbe793f94'
            Date:
              schema:
                type: string
                description: Current server date and time
                example: 'Thu, 24 Jan 2019 13:03:49 GMT'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '500':
          description: Internal Server Error
          headers:
            X-Request-ID:
              schema:
                type: string
                format: uuid
                description: Unique id of current request, to match records in log
                example: 'f7314976-f9fc-450f-b46e-b77fbe793f94'
            Date:
              schema:
                type: string
                description: Current server date and time
                example: 'Thu, 24 Jan 2019 13:03:49 GMT'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

  /_health:
    get:
      tags:
        - Health
      summary: Health check
      operationId: healthCheck
      responses:
        '200':
          description: empty object that means all ok
          headers:
            X-Request-ID:
              schema:
                type: string
                format: uuid
                description: Unique id of current request, to match records in log
                example: 'f7314976-f9fc-450f-b46e-b77fbe793f94'
            Date:
              schema:
                type: string
                description: Current server date and time
                example: 'Thu, 24 Jan 2019 13:03:49 GMT'
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
          headers:
            X-Request-ID:
              schema:
                type: string
                format: uuid
                description: Unique id of current request, to match records in log
                example: 'f7314976-f9fc-450f-b46e-b77fbe793f94'
            Date:
              schema:
                type: string
                description: Current server date and time
                example: 'Thu, 24 Jan 2019 13:03:49 GMT'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

components:
  schemas:
    Response:
      type: object
      required:
        - messages
      properties:
        messages:
          type: array
          items:
            type: string
